apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: influxdb
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086